config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'orders/index'
    get 'orders/show'
    get '/search', to: 'search#search'
  end
  namespace :public do
    get 'cart_products/index'
    get '/search', to: 'search#search'
  end
  namespace :admin do
    get 'genres/index'
    get 'genres/edit'
  end

  root to: 'homes#top'
  get      'homes/about' => 'homes#about', as: 'about'


  devise_for :customers, controllers: {
    registrations: 'public/customers/registrations',
    sessions:      'public/customers/sessions',
    passwords:     'public/customers/passwords'
  }

  namespace :admin do
    devise_for :admins, controllers: {
      sessions:      'admin/admins/sessions',
      registrations: 'admin/admins/registrations',
      passwords:     'admin/admins/passwords'
    }
    resources :products
    resources :genres,         only:[:index, :create, :edit, :update]
    resources :customers,      only:[:index, :show, :edit, :update] do
      get 'customer_orders' => 'orders#customer_order_index', as: 'orders'
    end
    resources :orders,         only:[:index, :show, :update]
    resources :order_products, only: [:update]
  end

  namespace :public do
    get       '/customer/confirm'             => 'customers#withdraw_confirm', as: 'confirm_withdraw'
    patch     '/customers/withdraw'           => 'customers#withdraw',         as: 'withdraw_customer'
    get       'orders/confirm'                => 'orders#confirm',             as: 'orders_confirm'
    get       'orders/thanks'                 => 'orders#thanks',              as: 'orders_thanks'
    post      'orders/new_distination'        => 'orders#new_distination',     as: 'orders_new_distination'
    post      'orders/create_order'           => 'orders#create_order',        as: 'orders_create_order'
    resources :products,      only: [:index, :show] do
      resource :likes,        only: [:create, :destroy]
    end
    resources :customers,     only: [:show, :withdraw_confirm, :edit, :update, :withdraw] do
      resources :likes,       only: [:index]
    end

    resources :distinations,  only: [:index, :create, :edit, :update, :destroy]
    resources :cart_products, only: [:index]
    resources :orders,        only: [:new, :create, :index, :show]

    post      'cart_products'                 => 'cart_products#create',      as: 'add_cart_products'
    patch     'cart_products/:id/:product_id' => 'cart_products#update',      as: 'update_cart_products'
    delete    'cart_products/:id/:product_id' => 'cart_products#destroy',     as: 'destroy_cart_products'
    delete    'cart_products'                 => 'cart_products#all_destroy', as: 'all_destroy'
    get       'product_sort'                  => 'products#sort',             as: 'product_sort'
  end

  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name,        presence: true
  validates :first_name,       presence: true
  validates :last_name_kana,   presence: true
  validates :first_name_kana,  presence: true
  validates :email,            presence: true,
                               uniqueness: true,
                               format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i}
  validates :postal_code,      presence: true
  validates :address,          presence: true
  validates :telephone_number, presence: true


  validates :password,         presence: true, on: :create

  has_many :cart_products,  dependent: :destroy
  has_many :distinations,   dependent: :destroy
  has_many :orders,         dependent: :destroy
  has_many :likes,          dependent: :destroy

  # ユーザーの'is_deleted'をタイムスタンプで更新
  def soft_delete
    update_attribute(:is_deleted, Time.current)
  end

  # ユーザーのアカウントが有効であることを確認しています
  def active_for_authentication?
    super && !is_deleted
  end

  # 削除したユーザーにメッセージを追加します
  def inactive_message
    !is_deleted ? super : :"アカウントは削除されています"
  end

  def self.search_for(content, method)
      Customer.where('last_name || first_name LIKE ?', '%'+content+'%')
  end


end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  before_action :authenticate_admin_admin!

  def index
    customers = Customer.all
    @customers = Kaminari.paginate_array(customers).page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
     @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "変更内容を保存しました"
      redirect_to admin_customer_path
    else
      flash.now[:alert] = '変更内容を保存できませんでした'
      render "edit"
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <h2 class='mt-5'><%= @customer.last_name + @customer.first_name %>さんの会員詳細</h2>
    <%= render 'layouts/errors_messages', model: @customer %>
    <%= form_with model: @customer, url: admin_customer_path, local: true do |f| %>

        <div class="row mt-5">
          <div class="col-md-3">会員ID</div>
          <div class="col-md-5"><%= @customer.id %></div>
        </div>

        <form class="form-horizontal">
          <div class="form-group form-row mt-3">
            <label class="col-md-3 control-label"><%= f.label :名前 %></label></br>
            <div class="col-md-2"><%= f.text_field :last_name, autofocus: true, class: "form-control" %></div>
            <div class="col-md-2"><%= f.text_field :first_name, class: "form-control" %></div>
          </div>

          <div class="form-group form-row">
            <label class="col-md-3 control-label"><%= f.label :フリガナ %></label></br>
            <div class="col-md-2"><%= f.text_field :last_name_kana, class: "form-control" %></div>
            <div class="col-md-2"><%= f.text_field :first_name_kana, class: "form-control" %></div>
          </div>

          <div class="form-group form-row">
            <label class="col-md-3 control-label"><%= f.label :メールアドレス %></label>
            <div class="col-md-4"><%= f.email_field :email, autocomplete: "email", class: "form-control" %></div>
          </div>

          <div class="form-group form-row">
            <label class="col-md-3 control-label"><%= f.label :郵便番号（ハイフンなし） %></label>
            <div class="col-md-4"><%= f.text_field :postal_code, class: "form-control" %></div>
          </div>

          <div class="form-group form-row">
            <label class="col-md-3 control-label"><%= f.label :住所 %></label>
            <div class="col-md-8"><%= f.text_field :address, class: "form-control" %></div>
          </div>

          <div class="form-group form-row">
            <label class="col-md-3 control-label"><%= f.label :電話番号（ハイフンなし） %></label>
            <div class="col-md-4"><%= f.telephone_field :telephone_number, class: "form-control" %></div>
          </div>

          <div class="form-group form-row">
            <label class="col-md-3 control-label"><%= f.label :会員ステータス %></label>
            <div class="col-md-4"><label class="mr-2"><%= f.radio_button :is_deleted, false %>有効</label>
                                  <label><%= f.radio_button :is_deleted, true %>退会</label>
            </div>
          </div>

          <div class="actions">
            <div class="col-md-5"><%= f.submit "変更を保存", class: 'btn btn-success' %></div>
          </div>
      </form>
    <% end %>
</div>

app/views/admin/customers/index.html.erb
<%= render 'layouts/admin_search' %>
<div class="container">
    <div class="col-2"></div>
    <div class="col-8 offset-2">
      <h5 class="d-table" style="background-color: #e6e3de;">　会員一覧　</h5>
      <table class="table table-bordered text-center mt-5">
        <thead class="thead-light">
          <tr><th>会員ID</th><th>氏名</th><th>メールアドレス</th><th>ステータス</th></tr>
        </thead>
          <% @customers.each do |customer| %>
            <tbody>
              <tr>
                <td><%= customer.id %></td>
                <td><%= link_to customer.last_name + customer.first_name, admin_customer_path(customer.id) %></td>
                <td><%= customer.email %></td>
                <td><% if customer.is_deleted == false %>
                      <p class="text-success">有効</p>
                    <% else %>
                      <p class="text-danger">無効</p>
                    <% end %>
                </td>
              </tr>
            </tbody>
          <% end %>
      </table>
    </div>
  </div>

app/views/admin/customers/show.html.erb
<div class="container">
  <h2 class='mt-5'><%= @customer.last_name + @customer.first_name %>さんの会員詳細</h2>
    <div class="customer-show my-3">
      <div class="row mt-5">
        <div class="col-md-3">会員ID</div>
        <div class="col-md-5"><%= @customer.id  %></div>
      </div>

      <div class="row mt-3">
        <div class="col-md-3">氏名</div>
        <div class="col-md-5"><%= @customer.last_name + @customer.first_name  %></div>
      </div>

      <div class="row mt-3">
        <div class="col-md-3">フリガナ</div>
        <div class="col-md-5"><%= @customer.last_name_kana + @customer.first_name_kana  %></div>
      </div>

      <div class="row mt-3">
        <div class="col-md-3">郵便番号</div>
        <div class="col-md-5"><%= @customer.postal_code  %></div>
      </div>

      <div class="row mt-3">
        <div class="col-md-3">住所</div>
        <div class="col-md-5"><%= @customer.address  %></div>
      </div>

      <div class="row mt-3">
        <div class="col-md-3">電話番号</div>
        <div class="col-md-5"><%= @customer.telephone_number  %></div>
      </div>

      <div class="row mt-3">
        <div class="col-md-3">メールアドレス</div>
        <div class="col-md-5"><%= @customer.email  %></div>
      </div>

      <div class="row mt-3">
        <div class="col-md-3">会員ステータス</div>
        <div class="col-md-5"><% if @customer.is_deleted == false %>
                                <p class="text-success">有効</p>
                              <% else %>
                                <p class="text-danger">無効</p>
                              <% end %>
        </div>
      </div>
    </div>
    <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-success mr-3" %>
    <%= link_to "注文履歴一覧を見る", admin_customer_orders_path(customer_id: @customer), class: "btn btn-info" %>
    <%= link_to "会員一覧に戻る＞", admin_customers_path, class: "btn" %>
  </div>