config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'orders/index'
    get 'orders/show'
    get '/search', to: 'search#search'
  end
  namespace :public do
    get 'cart_products/index'
    get '/search', to: 'search#search'
  end
  namespace :admin do
    get 'genres/index'
    get 'genres/edit'
  end

  root to: 'homes#top'
  get      'homes/about' => 'homes#about', as: 'about'


  devise_for :customers, controllers: {
    registrations: 'public/customers/registrations',
    sessions:      'public/customers/sessions',
    passwords:     'public/customers/passwords'
  }

  namespace :admin do
    devise_for :admins, controllers: {
      sessions:      'admin/admins/sessions',
      registrations: 'admin/admins/registrations',
      passwords:     'admin/admins/passwords'
    }
    resources :products
    resources :genres,         only:[:index, :create, :edit, :update]
    resources :customers,      only:[:index, :show, :edit, :update] do
      get 'customer_orders' => 'orders#customer_order_index', as: 'orders'
    end
    resources :orders,         only:[:index, :show, :update]
    resources :order_products, only: [:update]
  end

  namespace :public do
    get       '/customer/confirm'             => 'customers#withdraw_confirm', as: 'confirm_withdraw'
    patch     '/customers/withdraw'           => 'customers#withdraw',         as: 'withdraw_customer'
    get       'orders/confirm'                => 'orders#confirm',             as: 'orders_confirm'
    get       'orders/thanks'                 => 'orders#thanks',              as: 'orders_thanks'
    post      'orders/new_distination'        => 'orders#new_distination',     as: 'orders_new_distination'
    post      'orders/create_order'           => 'orders#create_order',        as: 'orders_create_order'
    resources :products,      only: [:index, :show] do
      resource :likes,        only: [:create, :destroy]
    end
    resources :customers,     only: [:show, :withdraw_confirm, :edit, :update, :withdraw] do
      resources :likes,       only: [:index]
    end

    resources :distinations,  only: [:index, :create, :edit, :update, :destroy]
    resources :cart_products, only: [:index]
    resources :orders,        only: [:new, :create, :index, :show]

    post      'cart_products'                 => 'cart_products#create',      as: 'add_cart_products'
    patch     'cart_products/:id/:product_id' => 'cart_products#update',      as: 'update_cart_products'
    delete    'cart_products/:id/:product_id' => 'cart_products#destroy',     as: 'destroy_cart_products'
    delete    'cart_products'                 => 'cart_products#all_destroy', as: 'all_destroy'
    get       'product_sort'                  => 'products#sort',             as: 'product_sort'
  end

  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/product.rb
class Product < ApplicationRecord

  attachment :image

  belongs_to :genre

  has_many :cart_products

  has_many :order_products, dependent: :destroy

  has_many :likes, dependent: :destroy

  validates :name,  presence: true
  validates :genre_id,  presence: true
  validates :image,  presence: true
  validates :introduction,  presence: true
  validates :price,  presence: true

  def self.search_for(content, method)
      Product.where('conversion_name LIKE ?', '%'+content+'%')
  end

  def liked_by?(customer)
    likes.where(customer_id: customer.id).exists?
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  before_action :authenticate_admin_admin!
  before_action :set_genres, only: [:new, :create, :edit, :update]

  def index
    products = Product.order(created_at: :asc)
    @products = Kaminari.paginate_array(products).page(params[:page]).per(8)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.name.match(/[一-龠々]/)
      @product.conversion_name = @product.name.to_kanhira.to_roman
    elsif @product.name.is_hira? || @product.name.is_kana?
      @product.conversion_name = @product.name.to_roman
    else
      @product.conversion_name = @product.name
    end
    if @product.save
      redirect_to admin_product_path(@product), notice: "商品を登録しました"
    else
      render "new"
    end
  end

  def show
    @product = Product.find(params[:id])
    tax = 1.1
    @tax_price = @product.price * tax
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.name.match(/[一-龠々]/)
      @product.conversion_name = @product.name.to_kanhira.to_roman
    elsif @product.name.is_hira? || @product.name.is_kana?
      @product.conversion_name = @product.name.to_roman
    else
      @product.conversion_name = @product.name
    end    
    if @product.update(product_params)
      redirect_to admin_product_path(@product), notice: "商品情報を編集しました"
    else
      render :edit
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :image, :introduction, :price, :genre_id, :is_active)
  end
  
  def set_genres
    @genres = Genre.all
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h5 class="mt-3 mb-5 d-table" style="background-color: #e6e3de;">　商品編集　</h5>
      <div class="mx-auto d-table">
        <%= form_with model: [:admin, @product], local: true do |f| %>
        <%= render 'layouts/errors_messages', model: f.object %>
          <div class="d-flex">
            <p style="width: 150px;">商品画像</p>
            <%= f.attachment_field :image, placeholder: "ファイルを選択" %>
          </div>
          <div class="d-flex my-3">
            <p style="width: 150px;">商品名</p>
            <%= f.text_field :name, size: "40", placeholder: "商品名" %>
          </div>
          <div class="d-flex">
            <p style="width: 150px;">商品説明</p>
            <%= f.text_area :introduction, size: "40x5", placeholder: "ここに説明文を記述します" %>
          </div>
          <div class="d-flex my-3">
            <p style="width: 150px;">ジャンル</p>
            <%= f.collection_select :genre_id, @genres, :id, :name, { include_blank: "--選択してください--　" } %>
          </div>
          <div class="d-flex">
            <p style="width: 150px;">税抜価格</p>
            <%= f.text_field :price, size: "40", placeholder: "1000" %><div class="mt-3 ml-1">円</div>
          </div>
          <div class="d-flex my-3">
            <p style="width: 150px;">販売ステータス</p>
            <%= f.radio_button :is_active, :true, class: "mr-1 mt-1" %>
            <%= f.label :is_active, "販売中", {value: :true, style: "display: inline-block;"} %>
            <%= f.radio_button :is_active, :false, class: "mr-1 ml-3 mt-1" %>
            <%= f.label :is_active, "販売停止中", {value: :false, style: "display: inline-block;"} %>
          </div>
          <div class="text-center"><%= f.submit "変更を保存", class: "btn btn-success btn-lg" %></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<%= render 'layouts/admin_search' %>
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <h5 class="mb-3 d-table" style="background-color: #e6e3de;">　商品一覧　</h5>
      <div class="text-right mb-2 mr-2"><%= link_to " 商品の新規登録", new_admin_product_path, class: "fas fa-plus" %></div>
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th>商品ID</th>
              <th>商品名</th>
              <th>税抜価格</th>
              <th>ジャンル</th>
              <th>ステータス</th>
            </tr>
          </thead>
          <% @products.each do |product| %>
            <tbody>
              <tr>
                <td><%= product.id %></td>
                <td><%= link_to "#{product.name}", admin_product_path(product) %></td>
                <td><%= product.price.to_s(:delimited) %></td>
                <td><%= Genre.find_by(id: product.genre_id).name %></td>
                <% if product.is_active? %>
                  <td class="text-success">販売中</td>
                <% else %>
                  <td class="text-secondary">販売停止中</td>
                <% end %>
              </tr>
            </tbody>
          <% end %>
        </table>
      <%= paginate @products %>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h5 class="mt-3 mb-5 d-table" style="background-color: #e6e3de;">　商品新規登録　</h5>
      <div class="mx-auto d-table">
        <%= form_with model: [:admin, @product], local: true do |f| %>
          <div class="d-flex">
            <p style="width: 150px;">商品画像</p>
            <%= f.attachment_field :image, placeholder: "ファイルを選択" %>
          </div>
          <div class="d-flex my-3">
            <p style="width: 150px;">商品名</p>
            <%= f.text_field :name, size: "40", placeholder: "商品名" %>
          </div>
          <div class="d-flex">
            <p style="width: 150px;">商品説明</p>
            <%= f.text_area :introduction, size: "40x5", placeholder: "ここに説明文を記述します" %>
          </div>
          <div class="d-flex my-3">
            <p style="width: 150px;">ジャンル</p>
            <%= f.collection_select :genre_id, Genre.all, :id, :name, { include_blank: "--選択してください--　" } %>
          </div>
          <div class="d-flex">
            <p style="width: 150px;">税抜価格</p>
            <%= f.text_field :price, size: "40", placeholder: "1000" %><div class="mt-3 ml-1">円</div>
          </div>
          <div class="d-flex my-3">
            <p style="width: 150px;">販売ステータス</p>
            <%= f.radio_button :is_active, :true, class: "mr-1 mt-1" %>
            <%= f.label :is_active, "販売中", {value: :true, style: "display: inline-block;"} %>
            <%= f.radio_button :is_active, :false, class: "mr-1 ml-3 mt-1" %>
            <%= f.label :is_active, "販売停止中", {value: :false, style: "display: inline-block;"} %>
          </div>
          <div class="text-center"><%= f.submit "新規登録", class: "btn btn-success btn-lg" %></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/show.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-md-8 offset-2 d-flex">
      <h5 class="mt-3 mb-5 d-table" style="background-color: #e6e3de;">　商品詳細　</h5>
    </div>
    <div class="col-md-8 offset-2 d-flex">
      <div class="mr-3">
        <%= attachment_image_tag @product, :image, size: '250x200', format:'jpeg', fallback: 'sample.jpg', class: "mr-5" %>
      </div>
      <div>
        <div class="d-flex">
          <p class="col-4">商品名</p>
          <h5><%= @product.name %></h5>
        </div>
        <div class="d-flex">
          <p class="col-4">商品説明</p>
          <h5 class="my-2"><%= @product.introduction %></h5>
        </div>
        <div class="d-flex">
          <p class="col-4">ジャンル</p>
          <h5 class="mt-5 mb-3"></h5>
        </div>
        <div class="d-flex">
          <p class="col-4">税込価格<br>(税抜価格)</p>
          <h5 class="font-weight-normal"><%= @tax_price.to_i.to_s(:delimited) %> (<%= @product.price.to_s(:delimited) %>) 円</h5>
        </div>
        <div class="d-flex">
          <p class="col-4">販売ステータス</p>
          <% if @product.is_active? %>
            <h5 class="text-success">販売中</h5>
          <% else %>
            <h5 class="text-secondary">販売停止中</h5>
          <% end %>
        </div>
        <div class="text-center">
          <%= link_to "編集する", edit_admin_product_path, class: "btn btn-lg btn-success mt-5" %>
        </div>
      </div>
    </div>
  </div>
</div>