config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'orders/index'
    get 'orders/show'
    get '/search', to: 'search#search'
  end
  namespace :public do
    get 'cart_products/index'
    get '/search', to: 'search#search'
  end
  namespace :admin do
    get 'genres/index'
    get 'genres/edit'
  end

  root to: 'homes#top'
  get      'homes/about' => 'homes#about', as: 'about'


  devise_for :customers, controllers: {
    registrations: 'public/customers/registrations',
    sessions:      'public/customers/sessions',
    passwords:     'public/customers/passwords'
  }

  namespace :admin do
    devise_for :admins, controllers: {
      sessions:      'admin/admins/sessions',
      registrations: 'admin/admins/registrations',
      passwords:     'admin/admins/passwords'
    }
    resources :products
    resources :genres,         only:[:index, :create, :edit, :update]
    resources :customers,      only:[:index, :show, :edit, :update] do
      get 'customer_orders' => 'orders#customer_order_index', as: 'orders'
    end
    resources :orders,         only:[:index, :show, :update]
    resources :order_products, only: [:update]
  end

  namespace :public do
    get       '/customer/confirm'             => 'customers#withdraw_confirm', as: 'confirm_withdraw'
    patch     '/customers/withdraw'           => 'customers#withdraw',         as: 'withdraw_customer'
    get       'orders/confirm'                => 'orders#confirm',             as: 'orders_confirm'
    get       'orders/thanks'                 => 'orders#thanks',              as: 'orders_thanks'
    post      'orders/new_distination'        => 'orders#new_distination',     as: 'orders_new_distination'
    post      'orders/create_order'           => 'orders#create_order',        as: 'orders_create_order'
    resources :products,      only: [:index, :show] do
      resource :likes,        only: [:create, :destroy]
    end
    resources :customers,     only: [:show, :withdraw_confirm, :edit, :update, :withdraw] do
      resources :likes,       only: [:index]
    end

    resources :distinations,  only: [:index, :create, :edit, :update, :destroy]
    resources :cart_products, only: [:index]
    resources :orders,        only: [:new, :create, :index, :show]

    post      'cart_products'                 => 'cart_products#create',      as: 'add_cart_products'
    patch     'cart_products/:id/:product_id' => 'cart_products#update',      as: 'update_cart_products'
    delete    'cart_products/:id/:product_id' => 'cart_products#destroy',     as: 'destroy_cart_products'
    delete    'cart_products'                 => 'cart_products#all_destroy', as: 'all_destroy'
    get       'product_sort'                  => 'products#sort',             as: 'product_sort'
  end

  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord

  belongs_to :product
  belongs_to :customer

  validates :product_id,  presence: true
  validates :customer_id,  presence: true
  validates :quantity,  presence: true

  def subtotal(price, quantity)
		quantity * (price * 1.10).round
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name,        presence: true
  validates :first_name,       presence: true
  validates :last_name_kana,   presence: true
  validates :first_name_kana,  presence: true
  validates :email,            presence: true,
                               uniqueness: true,
                               format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i}
  validates :postal_code,      presence: true
  validates :address,          presence: true
  validates :telephone_number, presence: true


  validates :password,         presence: true, on: :create

  has_many :cart_products,  dependent: :destroy
  has_many :distinations,   dependent: :destroy
  has_many :orders,         dependent: :destroy
  has_many :likes,          dependent: :destroy

  # ユーザーの'is_deleted'をタイムスタンプで更新
  def soft_delete
    update_attribute(:is_deleted, Time.current)
  end

  # ユーザーのアカウントが有効であることを確認しています
  def active_for_authentication?
    super && !is_deleted
  end

  # 削除したユーザーにメッセージを追加します
  def inactive_message
    !is_deleted ? super : :"アカウントは削除されています"
  end

  def self.search_for(content, method)
      Customer.where('last_name || first_name LIKE ?', '%'+content+'%')
  end


end

app/models/distination.rb
class Distination < ApplicationRecord
  validates :postal_code, presence: true
  validates :address,     presence: true
  validates :name,        presence: true
  
  belongs_to :customer
  
  def full_address
    "〒#{self.postal_code}　#{self.address}　#{self.name}"
  end
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :products
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, format: {with: VALID_EMAIL_REGEX}, allow_blank: true
  validates :name,  presence: true
  
  def self.search_for(content, method)
      Genre.where('conversion_name LIKE ?', '%'+content+'%') 
  end

end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :customer
  belongs_to :product

end

app/models/order.rb
class Order < ApplicationRecord

  validates  :customer_id,    presence: true
  validates  :post_code,      presence: true
  validates  :address,        presence: true
  validates  :name,           presence: true
  validates  :shipping,       presence: true
  validates  :total_price,    presence: true
  validates  :payment,        presence: true
  validates  :order_status,   presence: true

  belongs_to :customer
  has_many :order_products,   dependent: :destroy

  enum order_status: { "入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4 }
  enum payment: { "クレジットカード": 0, "銀行振込": 1 }

end

app/models/order_product.rb
class OrderProduct < ApplicationRecord

  belongs_to :order
  belongs_to :product

  enum product_status: { "着手待ち": 0, "製作待ち": 1, "製作中": 2, "製作完了": 3}

  def subtotal(price, quantity)
		quantity * (price * 1.10).round
  end

end

app/models/product.rb
class Product < ApplicationRecord

  attachment :image

  belongs_to :genre

  has_many :cart_products

  has_many :order_products, dependent: :destroy

  has_many :likes, dependent: :destroy

  validates :name,  presence: true
  validates :genre_id,  presence: true
  validates :image,  presence: true
  validates :introduction,  presence: true
  validates :price,  presence: true

  def self.search_for(content, method)
      Product.where('conversion_name LIKE ?', '%'+content+'%')
  end

  def liked_by?(customer)
    likes.where(customer_id: customer.id).exists?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_orders_path
    when Customer
      public_customer_path(current_customer)
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @products = Product.order(created_at: :desc).limit(4)
  end

  def about
    @products = Product.all
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/distinations_helper.rb
module DistinationsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/admin/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_admin_search.html.erb
<div class="container mt-3">
<div class="search-form text-right">
  <%= form_with url: admin_search_path, method: :get, local: true do |f| %>
    <%= f.text_field :content %>
    <%= f.select :model, options_for_select({ "会員" => "customer", "商品名" => "product" }) %>
    <button type="submit" class="btn btn-sm btn-secondary">
      <i class="fas fa-search"></i> 検索
    </button>
  <% end %>
</div>
</div>

app/views/layouts/_customer_search.html.erb
  <div class="container mt-3">
  <div class="search-form text-right">
  <%= form_with url: public_search_path, method: :get, local: true do |f| %>
    <%= f.text_field :content %>
    <button type="submit" class="btn btn-sm btn-secondary">
      <i class="fas fa-search"></i> 検索
    </button>
  <% end %>
</div>
</div>

app/views/layouts/_errors_messages.html.erb
<% if model.errors.any? %>
<div class="border border-danger mb-3">
  <div class="bg-danger text-light pl-2"><%= model.errors.count %>件のエラーが発生しました</div>
  <% model.errors.full_messages.each do |message| %>
  <ul>
    <li class="ml-4"><%= message %></li>
  </ul>
  <% end %>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
    <% unless request.path.include?("admin") %>
      <h5 class="p-2 pl-4 underbar">お問い合わせ</h5>
      <div class="d-flex">
        <p class="p-2 pl-4">
          ながのCake<br>
          〒123-0023 東京都新宿区xxxxx<br>
          TEL:045-264-4076<br>
          MAIL:info@nagano_cake.jp
        </p>
        <div class="col-3 text-right d-flex mt-auto pb-3">
          <h4 class="fab fa-facebook-square"></h4>
          <h4 class="fab fa-twitter-square mx-2"></h4>
          <a href='https://www.instagram.com/p/CQiwKp_D5Na/?utm_medium=copy_link'>
            <h4 class="fab fa-instagram-square"></h4>
          </a>
        </div>
      </div>
   <% end %>
      <div class="d-table mx-auto my-3">CopyRight 2021 nagano_cake</div>
  </div>
</footer>

app/views/layouts/_header.html.erb
  <nav class="navbar navbar-expand-lg navbar-light border-bottom">
    <div class="container" style="height:100px">
      <div class="navbar-brand pt-3">
        <% if admin_admin_signed_in? %>
          <%= link_to admin_orders_path, data: {"turbolinks" => false} do %>
            <%= image_tag "logo.png", :size => '330x60' %>
          <% end %>
        <% else %>
          <%= link_to root_path, data: {"turbolinks" => false} do %>
            <%= image_tag "logo.png", :size => '330x60' %>
          <% end %>
        <% end %>
      </div>

      <div>
      <ul class="navbar-nav mb-2">
        <% if customer_signed_in? %>
          <li class="nav-item ml-auto">ようこそ<%= current_customer.last_name %>さん！</li>
        <% end %>
      </ul>

      <div class="collapse navbar-collapse" id="sp-menu">

        <ul class="navbar-nav ml-auto">
          <% if admin_admin_signed_in? %>
          <li class="mr-4 nav-item"><%= link_to '商品一覧',  admin_products_path, class: "nav-link text-dark" %></li>
          <li class="mr-4 nav-item"><%= link_to '会員一覧', admin_customers_path, class: "nav-link text-dark" %></li>
          <li class="mr-4 nav-item"><%= link_to '注文履歴一覧', admin_orders_path, data: {"turbolinks" => false}, class: "nav-link text-dark" %></li>
          <li class="mr-4 nav-item"><%= link_to 'ジャンル一覧', admin_genres_path, class: "nav-link text-dark" %></li>
          <li class="mr-4 nav-item"><%= link_to 'ログアウト', destroy_admin_admin_session_path, class: "nav-link text-dark", method: :delete %></li>
          <% elsif customer_signed_in? %>
          <li class="mr-4 nav-item"><%= link_to 'MY PAGE', public_customer_path(current_customer), class: "nav-link text-dark" %></li>
          <li class="mr-4 nav-item"><%= link_to 'PRODUCTS', public_products_path, class: "nav-link text-dark" %></li>
          <li class="mr-4 nav-item"><%= link_to 'MY CART', public_cart_products_path, class: "nav-link text-dark" %></li>
          <li class="mr-4 nav-item"><%= link_to 'LOG OUT', destroy_customer_session_path, class: "nav-link text-dark", method: :delete %></li>
          <% else %>
          <li class="mr-4 nav-item"><%= link_to 'ABOUT', about_path, class: "nav-link text-dark" %></li>
          <li class="mr-4 nav-item"><%= link_to 'PRODUCTS', public_products_path, class: "nav-link text-dark" %></li>
          <li class="mr-4 nav-item"><%= link_to 'SIGN UP', new_customer_registration_path, class: "nav-link text-dark" %></li>
          <li class="mr-4 nav-item"><%= link_to 'LOG IN', new_customer_session_path, class: "nav-link text-dark" %></li>
          <% end %>
        </ul>
        </div>
      <div id="hm-icon">
      <a class="menu-trigger" href="#">
        <span></span>
        <span></span>
        <span></span>
      </a>
    </div>
      </div>
</div>
  </nav>

app/views/layouts/_search.html.erb
<div class="container">
<div class="search-form text-right">
  <%= form_with url: admin_search_path, method: :get, local: true do |f| %>
    <%= f.text_field :content %>
    <%= f.select :model, options_for_select({ "Customer" => "customer", "Product" => "product" }) %>
    <%= f.submit '検索' %>
  <% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
     <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
    <%= favicon_link_tag('favicon.ico') %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="title-header bg-white">
      <%= render 'layouts/header' %>
    </header>
    <% flash.each do |message_type, message| %>
      <% if message_type == "alert" %>
        <div class="fade show alert alert-danger d-flex">
          <%= content_tag :div, message %>
          <button class="close ml-auto" data-dismiss="alert"> &times; </button>
        </div>
      <% else %>
        <div class="fade show alert alert-success d-flex">
          <%= content_tag :div, message %>
          <button class="close ml-auto" data-dismiss="alert"> &times; </button>
        </div>
      <% end %>
    <% end %>
    <%= yield %>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>