config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'orders/index'
    get 'orders/show'
    get '/search', to: 'search#search'
  end
  namespace :public do
    get 'cart_products/index'
    get '/search', to: 'search#search'
  end
  namespace :admin do
    get 'genres/index'
    get 'genres/edit'
  end

  root to: 'homes#top'
  get      'homes/about' => 'homes#about', as: 'about'


  devise_for :customers, controllers: {
    registrations: 'public/customers/registrations',
    sessions:      'public/customers/sessions',
    passwords:     'public/customers/passwords'
  }

  namespace :admin do
    devise_for :admins, controllers: {
      sessions:      'admin/admins/sessions',
      registrations: 'admin/admins/registrations',
      passwords:     'admin/admins/passwords'
    }
    resources :products
    resources :genres,         only:[:index, :create, :edit, :update]
    resources :customers,      only:[:index, :show, :edit, :update] do
      get 'customer_orders' => 'orders#customer_order_index', as: 'orders'
    end
    resources :orders,         only:[:index, :show, :update]
    resources :order_products, only: [:update]
  end

  namespace :public do
    get       '/customer/confirm'             => 'customers#withdraw_confirm', as: 'confirm_withdraw'
    patch     '/customers/withdraw'           => 'customers#withdraw',         as: 'withdraw_customer'
    get       'orders/confirm'                => 'orders#confirm',             as: 'orders_confirm'
    get       'orders/thanks'                 => 'orders#thanks',              as: 'orders_thanks'
    post      'orders/new_distination'        => 'orders#new_distination',     as: 'orders_new_distination'
    post      'orders/create_order'           => 'orders#create_order',        as: 'orders_create_order'
    resources :products,      only: [:index, :show] do
      resource :likes,        only: [:create, :destroy]
    end
    resources :customers,     only: [:show, :withdraw_confirm, :edit, :update, :withdraw] do
      resources :likes,       only: [:index]
    end

    resources :distinations,  only: [:index, :create, :edit, :update, :destroy]
    resources :cart_products, only: [:index]
    resources :orders,        only: [:new, :create, :index, :show]

    post      'cart_products'                 => 'cart_products#create',      as: 'add_cart_products'
    patch     'cart_products/:id/:product_id' => 'cart_products#update',      as: 'update_cart_products'
    delete    'cart_products/:id/:product_id' => 'cart_products#destroy',     as: 'destroy_cart_products'
    delete    'cart_products'                 => 'cart_products#all_destroy', as: 'all_destroy'
    get       'product_sort'                  => 'products#sort',             as: 'product_sort'
  end

  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/controllers/admin/search_controller.rb
class Admin::SearchController < ApplicationController
 	def search
		@model = params[:model]
		@content = params[:content]
		@method = params[:method]
		if @model == 'customer'
			@records = Customer.search_for(@content, @method).page(params[:page]).reverse_order
		else
	    unless @content.blank?
         if @content.match(/[一-龠々]/)
          @record = @content.to_kanhira.to_roman
         elsif @content.is_hira? || @content.is_kana?
         @record = @content.to_roman
         else
          @record = @content
         end
        end
		 @records = Product.search_for(@record, @method).page(params[:page]).reverse_order
		end
	end

end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/admin/search/search.html.erb
<% if @model == 'customer' %>
<%= render 'layouts/admin_search' %>
  <div class="col-2"></div>
  <div class="col-8 offset-2">
    <h3>会員検索結果 "<%= @content %>"</h3>
    <h2 class='mt-5'>会員一覧</h2>
    <table class="table table-bordered text-center mt-5">
      <thead class="thead-light">
        <tr><th>会員ID</th><th>氏名</th><th>メールアドレス</th><th>ステータス</th></tr>
      </thead>
        <% @records.each do |customer| %>
          <tbody>
            <tr>
              <td><%= customer.id %></td>
              <td><%= link_to customer.last_name + customer.first_name, admin_customer_path(customer.id) %></td>
              <td><%= customer.email %></td>
              <td><% if customer.is_deleted == false %>
                    <p class="text-success">有効</p>
                  <% else %>
                    <p class="text-danger">無効</p>
                  <% end %>
              </td>
            </tr>
          </tbody>
        <% end %>
        </table>
         <% if @records.count == 0 %>
         <div>
          <h4 class="d-flex align-items-center justify-content-center" style="height: 200px;">該当する会員はいません</h4>
        </div>
        <% end %>
<% elsif @model == 'product'%>
<%= render 'layouts/admin_search' %>
  <div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1">
     <h3 class="mt-3">商品検索結果 "<%= @content %>"</h3>
      <h5 class="mt-3 mb-5 d-table" style="background-color: #e6e3de;">　商品一覧　</h5>
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th>商品ID</th>
              <th>商品名</th>
              <th>税抜価格</th>
              <th>ジャンル</th>
              <th>ステータス</th>
            </tr>
          </thead>
          <% @records.each do |product| %>
            <tbody>
              <tr>
                <td><%= product.id %></td>
                <td><%= link_to "#{product.name}", admin_product_path(product) %></td>
                <td><%= product.price.to_s(:delimited) %></td>
                <td><%= Genre.find_by(id: product.genre_id).name %></td>
                <% if product.is_active? %>
                  <td class="text-success">販売中</td>
                <% else %>
                  <td class="text-secondary">販売停止中</td>
                <% end %>
              </tr>
            </tbody>
          <% end %>
        </table>
        <% if @records.count == 0 %>
         <div>
          <h4 class="d-flex align-items-center justify-content-center" style="height: 200px;">該当する商品はありませんでした</h4>
        </div>
        <% end %>
    </div>
  </div>
</div>

<% end %>